service: oneforce-test
plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-openapi-documentation

functions:
 app: 
   handler: dist/lambda.handler
   events:
     - http:
        method: get
        path: /{users+}

provider: 
    name: aws
    runtime: nodejs14.x
    apiGateway:
      shouldStartNameWithService: true

    environment: 
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
      NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000
    iam: 
      role: 
        statements: 
            - Effect: 'Allow'
              Action: 
                - 'dynamodb:DescribeTable'
                - 'dynamodb:Query'
                - 'dynamodb:Scan'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:DeleteItem'

              Resource: arn:aws:dynamodb:eu-west-1:*:table/users

custom: 
    esbuild: 
      bundle: true
      minify: false
      sourcemap: true
      exclude: aws-sdk
      target: node14
      define: 'require.resolve: undefined'
      platform: node
      concurrency: 10

    dynamodb: 
      start: 
        port: 8000
        inMemory: true
        migrate: true

    documentation:
      version: '1'
      title: 'users API'
      description: 'users API for get list or current user'
      models: {}

      stages: dev  